import { StyleSheet, Platform } from 'react-native';

export const createStyles = (colors) => StyleSheet.create({
  container: {
    backgroundColor: colors.background,
    flex: 1,
  },
  scrollView: {
    flex: 1,
    width: '100%',
  },
  contentContainer: {
    padding: 24,
    alignItems: 'center',
    paddingBottom: 40,
  },

  header: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 10,
    marginTop: 10,
  },
  logoutText: {
    color: colors.textLight,
    fontSize: 14,
    fontWeight: '500',
    marginTop: 10,
  },
  themeIcon: {
    fontSize: 24,
    marginTop: 10,
  },
  themeToggle: {
    marginLeft: 'auto',
  },

  logo: {
    width: 230,
    height: 230,
    marginBottom: 10,
  },

  welcomeText: {
    fontSize: 18,
    fontWeight: '600',
    color: colors.text,
    marginBottom: 30,
    textAlign: 'center',
  },

  pickersRow: {
    width: '100%',
    maxWidth: 1190,
    flexDirection: 'row',
    gap: 16,
    marginBottom: 20,
  },
  pickerWrapper: {
    flex: 1,
    backgroundColor: colors.inputBg,
    borderRadius: 12,
    paddingTop: 8,
    borderWidth: 1,
    borderColor: colors.inputBorder,
  },
  pickerLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: colors.textLight,
    paddingHorizontal: 16,
    paddingBottom: 4,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  picker: {
    height: 50,
    color: colors.text,
    backgroundColor: 'transparent',
    marginHorizontal: 10,
    paddingLeft: 10,
    border: 0,
  },

  cardsRow: {
    width: '100%',
    maxWidth: 1200,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 20,
  },
  cardWrapper: {
    flex: 1,
    minWidth: 300,
  },

  card: {
    backgroundColor: colors.cardBg,
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: colors.inputBorder,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 3,
    width: '100%',
    maxWidth: 600,
  },
  inputHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  sectionLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.text,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 8,
    marginTop: 5,
  },
  clearButton: {
    color: colors.textLight,
    fontSize: 14,
  },
  input: {
    backgroundColor: colors.inputBg,
    borderRadius: 12,
    padding: 16,
    fontSize: 15,
    color: colors.text,
    minHeight: 40,
    textAlignVertical: 'top',
    borderWidth: 1,
    borderColor: colors.inputBorder,
    marginBottom: 8,
  },
  
  passwordContainer: {
    position: 'relative',
    width: '100%',
    marginBottom: 8,
  },
  passwordInput: {
    backgroundColor: colors.inputBg,
    borderRadius: 12,
    padding: 16,
    paddingRight: 50,
    fontSize: 15,
    color: colors.text,
    borderWidth: 1,
    borderColor: colors.inputBorder,
    width: '100%',
  },
  passwordToggle: {
    position: 'absolute',
    right: 12,
    top: '35%',
    transform: [{ translateY: -12 }],
    padding: 8,
    zIndex: 1,
  },
  passwordToggleIcon: {
    fontSize: 20,
  },

  characterCounter: {
    fontSize: 12,
    color: colors.textLight,
    textAlign: 'right',
    marginBottom: 10,
    marginRight: 4,
  },
  characterCounterWarning: {
    color: '#ff4444',
    fontWeight: '600',
  },
  errorContainer: {
    backgroundColor: colors.errorBg,
    borderRadius: 12,
    padding: 14,
    marginBottom: 16,
    borderLeftWidth: 4,
    borderLeftColor: colors.error,
  },
  errorText: {
    color: colors.error,
    fontSize: 14,
    fontWeight: '500',
  },
  button: {
    backgroundColor: colors.button,
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
    shadowColor: colors.button,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
    marginTop: 8,
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  buttonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '600',
  },

  resultCard: {
    backgroundColor: colors.resultBg,
    borderRadius: 16,
    padding: 20,
    minHeight: 140,
    borderWidth: 1,
    borderColor: colors.inputBorder,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 3,
  },
  resultLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.text,
    marginBottom: 12,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  resultText: {
    fontSize: 18,
    color: colors.text,
    lineHeight: 28,
    fontWeight: '500',
    paddingTop: 5,
    paddingLeft: 5,
  },
  resultTextRTL: {
    textAlign: 'right',
    writingDirection: 'rtl',
    paddingLeft: 10,
    paddingRight: 10,
  },
  resultPlaceholder: {
    backgroundColor: colors.cardBg,
    borderRadius: 16,
    padding: 20,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.inputBorder,
    borderStyle: 'dashed',
  },
  placeholderText: {
    color: colors.textLight,
    fontSize: 14,
    fontStyle: 'italic',
  },
  speakButton: {
    position: 'absolute',
    bottom: 10,
    left: 20,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.inputBg,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.inputBorder,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  speakIcon: {
    fontSize: 20,
  },
});